// COMPASS DESIGN SYSTEM - NAVIGATION (ADVANCED AUTO-DETECTION)
// This version uses a manifest file to auto-detect all pages

(function() {
  // ============================================================
  // NAVIGATION CONFIGURATION
  // ============================================================
  
  const navigationItems = [
    {
      title: 'Getting Started',
      items: [
        { name: 'Overview', href: 'index.html' }
      ]
    },
    {
      title: 'Foundation',
      items: [
        { name: 'Colors', href: 'colors.html' },
        { name: 'Typography', href: 'typography.html' }
      ]
    },
    {
      title: 'Components',
      items: [
        { name: 'Buttons', href: 'buttons.html' },
        { name: 'Certification Badges', href: 'badges.html' },
        { name: 'Status Indicators', href: 'status-indicators.html' },
        { name: 'Input Fields & Forms', href: 'forms.html' },
        { name: 'Accordion', href: 'accordion.html' },
        { name: 'Stepper', href: 'stepper.html' },
        { name: 'Snackbar', href: 'snackbar.html' },
        { name: 'Chips', href: 'chips.html' }
      ]
    },
    {
      title: 'Patterns',
      items: [
        { name: 'Product Cards', href: 'components.html' },
        { name: 'Examples', href: 'examples.html' }
      ]
    }
  ];

  // ============================================================
  // AUTO-DETECTION SETTINGS
  // ============================================================
  
  const CONFIG = {
    autoDetect: true,                    // Enable auto-detection
    manifestFile: 'pages-manifest.json', // Generated manifest file
    excludedPages: [                     // Pages to ignore
      '404.html',
      'test.html',
      'draft.html',
      'temp.html',
      'navigation.html'
    ],
    autoDetectSection: 'Other Pages',    // Section name for unlisted pages
    showNewBadge: true,                  // Show "New" badge on auto-detected pages
    sortAlphabetically: true             // Sort auto-detected pages A-Z
  };

  // ============================================================
  // UTILITY: Generate friendly name from filename
  // ============================================================
  
  function generateFriendlyName(filename) {
    return filename
      .replace('.html', '')
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  // ============================================================
  // AUTO-DETECTION: Load manifest and find unlisted pages
  // ============================================================
  
  async function getAutoDetectedPages() {
    if (!CONFIG.autoDetect) return [];
    
    try {
      // Try to load manifest file (generated by build script)
      const response = await fetch(CONFIG.manifestFile);
      
      if (!response.ok) {
        console.log('No manifest file found - auto-detection disabled');
        return fallbackAutoDetection();
      }
      
      const manifest = await response.json();
      
      // Get all explicitly listed pages
      const listedPages = new Set();
      navigationItems.forEach(section => {
        section.items.forEach(item => {
          listedPages.add(item.href);
        });
      });
      
      // Find unlisted pages
      const autoDetected = manifest.pages
        .filter(page => 
          !listedPages.has(page) && 
          !CONFIG.excludedPages.includes(page) &&
          page.endsWith('.html')
        )
        .map(page => ({
          name: generateFriendlyName(page),
          href: page,
          isAutoDetected: true
        }));
      
      // Sort if configured
      if (CONFIG.sortAlphabetically) {
        autoDetected.sort((a, b) => a.name.localeCompare(b.name));
      }
      
      return autoDetected;
      
    } catch (error) {
      console.log('Auto-detection error:', error.message);
      return fallbackAutoDetection();
    }
  }

  // ============================================================
  // FALLBACK: Check if current page is unlisted
  // ============================================================
  
  function fallbackAutoDetection() {
    const currentPage = window.location.pathname.split('/').pop() || 'index.html';
    
    // Get all listed pages
    const listedPages = new Set();
    navigationItems.forEach(section => {
      section.items.forEach(item => {
        listedPages.add(item.href);
      });
    });
    
    // If current page isn't listed, show it
    if (currentPage && 
        currentPage.endsWith('.html') && 
        !listedPages.has(currentPage) && 
        !CONFIG.excludedPages.includes(currentPage)) {
      
      return [{
        name: generateFriendlyName(currentPage),
        href: currentPage,
        isAutoDetected: true
      }];
    }
    
    return [];
  }

  // ============================================================
  // GENERATE NAVIGATION HTML
  // ============================================================
  
  async function generateNavigation() {
    const currentPage = window.location.pathname.split('/').pop() || 'index.html';
    let navHTML = '<aside class="sidenav">';
    
    // Add explicitly configured sections
    navigationItems.forEach(section => {
      navHTML += `
        <div class="sidenav-section">
          <div class="sidenav-section-title">${section.title}</div>
      `;
      
      section.items.forEach(item => {
        const isActive = currentPage === item.href ? 'active' : '';
        navHTML += `
          <a href="${item.href}" class="sidenav-item ${isActive}">
            ${item.name}
          </a>
        `;
      });
      
      navHTML += '</div>';
    });
    
    // Add auto-detected pages section
    const autoDetected = await getAutoDetectedPages();
    
    if (autoDetected.length > 0) {
      navHTML += `
        <div class="sidenav-section">
          <div class="sidenav-section-title">${CONFIG.autoDetectSection}</div>
      `;
      
      autoDetected.forEach(item => {
        const isActive = currentPage === item.href ? 'active' : '';
        const badge = CONFIG.showNewBadge ? '<span class="auto-detected-badge">New</span>' : '';
        
        navHTML += `
          <a href="${item.href}" class="sidenav-item ${isActive}">
            ${item.name}
            ${badge}
          </a>
        `;
      });
      
      navHTML += '</div>';
    }
    
    navHTML += '</aside>';
    return navHTML;
  }

  // ============================================================
  // INJECT NAVIGATION
  // ============================================================
  
  async function initNavigation() {
    const mainContent = document.querySelector('.main-content');
    
    if (mainContent) {
      const navHTML = await generateNavigation();
      mainContent.insertAdjacentHTML('beforebegin', navHTML);
      
      // Add styles for badges
      if (CONFIG.showNewBadge) {
        addAutoDetectedStyles();
      }
    }
  }

  // ============================================================
  // STYLING
  // ============================================================
  
  function addAutoDetectedStyles() {
    const style = document.createElement('style');
    style.textContent = `
      .auto-detected-badge {
        display: inline-block;
        margin-left: 8px;
        padding: 2px 6px;
        background: #FEF3C7;
        color: #F59E0B;
        font-size: 11px;
        font-weight: 600;
        border-radius: 4px;
        text-transform: uppercase;
        letter-spacing: 0.5px;
      }
      
      .sidenav-item:hover .auto-detected-badge {
        background: #FDE68A;
      }
    `;
    document.head.appendChild(style);
  }

  // ============================================================
  // INITIALIZE
  // ============================================================
  
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initNavigation);
  } else {
    initNavigation();
  }
})();
